version: '2'
services:
    db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            #- ./db_data:/docker-entrypoint-initdb.d
            - mysql_data:/var/lib/mysql
        networks:
            backend:
                ipv4_address: 172.20.1.10
        ports:
            - 3305:3306
    web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
            -  UPLOAD_LIMIT = 64M
        restart: unless-stopped
        networks:
            backend:
                ipv4_address: 172.20.1.20
        volumes:
            - ./public:/var/www/html/public
            - ./apache_log:/var/log/apache2
        ports:
            - 8000:80
        depends_on:
            - db
        links:
            - db
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            networks:
            UPLOAD_LIMIT: 64M
        networks:
            backend:
                ipv4_address: 172.20.1.30
    # nodejs:
    #     build:
    #         context: .
    #         dockerfile: docker/nodejs/Dockerfile
    #         args:
    #             uid: ${UID}
    #     restart: always
    #     networks:
    #         backend:
    #             ipv4_address: 172.20.1.40
    #     volumes:
    #         - ./docker/nodejs:/usr/src/app
    #     ports:
    #         - 49160:3000
    #     depends_on:
    #         - db
    #     links:
    #         - db


volumes:
    mysql_data:
    src:


networks:
  backend:
    ipam:
      config:
        - subnet: 172.20.1.0/24
